PREFIX : <http://7daystodie.gamepedia.com/#>

SELECT
  ?id
  ?fullness
  ?hydration
  ?health
  ?wellness
#  ?recItem
#  ?fullnessCost
#  ?hydrationCost
#  ?wellnessCost
  (?fullness - SUM(COALESCE(?fullnessCost, 0) * ?recCount) AS ?netFullnessCost)
  (?hydration - SUM(COALESCE(?hydrationCost, 0) * ?recCount) AS ?netHydrationCost)
  (?health - SUM(COALESCE(?healthCost, 0) * ?recCount) AS ?netHealthCost)  
  (?wellness - SUM(COALESCE(?wellnessCost, 0) * ?recCount) AS ?netWellnessCost)
  (?netFullnessCost + ?netHydrationCost + ?netHealthCost + ?netWellnessCost AS ?cost)

WHERE {
  ?id a :Food ;
    :fullness ?fullness ;
    :hydration ?hydration ;
    :health ?health ;
    :wellness ?wellness ;
    :recipe [
      :time ?time ;
      :items [
        :item ?recItem ;
        :count ?recCount
      ]
    ] .

  OPTIONAL { ?recItem :hydration ?hydrationCost }
  OPTIONAL { ?recItem :fullness  ?fullnessCost }
  OPTIONAL { ?recItem :health ?healthCost }
  OPTIONAL { ?recItem :wellness ?wellnessCost }
}
GROUP BY ?id ?fullness ?hydration ?wellness ?health
ORDER BY DESC(?cost) ?id
# ORDER BY ?id
